name: 'Enhancement'
description: 'File an enhancement ticket.'
title: '[Enhancement]  '
labels: []
projects:
  - 'saltshore/1'
assignees:
  - 'ndouglas'
body:
  - type: 'textarea'
    id: 'user-story'
    attributes:
      label: 'User Story'
      value: 'As a _____ I want _____ so I can ______.'
  - type: 'textarea'
    id: 'tasks'
    attributes:
      label: 'Tasks'
      value: |
        - [ ] Task 1
        - [ ] Task 2
  - type: 'textarea'
    id: 'acceptance-criteria'
    attributes:
      label: 'Acceptance Criteria'
      value: |
        - [ ] AC 1
        - [ ] AC 2
